name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Create Chrome zip
      run: bun run zip

    - name: Create Firefox zip
      run: bun run zip:firefox

    - name: Upload Chrome artifact
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: .output/figma-wakatime-1.0.0-chrome.zip
        if-no-files-found: error

    - name: Upload Firefox artifact
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: .output/figma-wakatime-1.0.0-firefox.zip
        if-no-files-found: error