name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build extensions
      run: |
        bun run build
        bun run build:firefox

    - name: Upload Chrome artifact
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: .output/chrome-mv3
        if-no-files-found: error

    - name: Upload Firefox artifact
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: .output/firefox-mv2
        if-no-files-found: error